<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Laskar Pelangi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/979-3062-79-7-L.jpg',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2005,
                'isbn' => '979-3062-79-7',
                'category' => 'Novel',
                'synopsis' => 'Novel inspiratif tentang perjuangan anak-anak Belitung mengejar pendidikan di tengah keterbatasan.',
                'shelf_code' => 'NVL-001',
                'stock' => 10,
            ],
            [
                'title' => 'Sang Pemimpi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/979-3062-88-6-L.jpg',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2006,
                'isbn' => '979-3062-88-6',
                'category' => 'Novel',
                'synopsis' => 'Kisah lanjutan Laskar Pelangi...',
                'shelf_code' => 'NVL-002',
                'stock' => 8,
            ],
            [
                'title' => 'Edensor',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/979-3062-99-1-L.jpg',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2007,
                'isbn' => '979-3062-99-1',
                'category' => 'Novel',
                'synopsis' => 'Petualangan Ikal dan Arai di Eropa...',
                'shelf_code' => 'NVL-003',
                'stock' => 7,
            ],
            [
                'title' => 'Negeri 5 Menara',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-979-22-4868-3-L.jpg',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2009,
                'isbn' => '978-979-22-4868-3',
                'category' => 'Novel Inspiratif',
                'synopsis' => 'Kisah enam santri dan motto Man Jadda Wajada.',
                'shelf_code' => 'NVL-004',
                'stock' => 12,
            ],
            [
                'title' => 'Rantau 1 Muara',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-03-0032-8-L.jpg',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2013,
                'isbn' => '978-602-03-0032-8',
                'category' => 'Novel Inspiratif',
                'synopsis' => 'Perjalanan Alif dalam mengejar cita-cita...',
                'shelf_code' => 'NVL-005',
                'stock' => 6,
            ],
            [
                'title' => 'Bumi Manusia',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-03-1212-3-L.jpg',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'year' => 1980,
                'isbn' => '978-602-03-1212-3',
                'category' => 'Sastra',
                'synopsis' => 'Kisah Minke dan perjuangannya...',
                'shelf_code' => 'SST-006',
                'stock' => 9,
            ],
            [
                'title' => 'Ronggeng Dukuh Paruk',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-979-22-3891-2-L.jpg',
                'author' => 'Ahmad Tohari',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 1982,
                'isbn' => '978-979-22-3891-2',
                'category' => 'Sastra',
                'synopsis' => 'Kisah Srintil dan budaya tradisional...',
                'shelf_code' => 'SST-007',
                'stock' => 8,
            ],
            [
                'title' => 'Ayat-Ayat Cinta',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-979-321-012-8-L.jpg',
                'author' => 'Habiburrahman El Shirazy',
                'publisher' => 'Republika',
                'year' => 2004,
                'isbn' => '978-979-321-012-8',
                'category' => 'Religi',
                'synopsis' => 'Kisah cinta dan iman Fahri di Mesir...',
                'shelf_code' => 'RLG-008',
                'stock' => 10,
            ],
            [
                'title' => 'Ketika Cinta Bertasbih',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-979-321-456-0-L.jpg',
                'author' => 'Habiburrahman El Shirazy',
                'publisher' => 'Republika',
                'year' => 2007,
                'isbn' => '978-979-321-456-0',
                'category' => 'Religi',
                'synopsis' => 'Kisah Azzam dalam perjalanan hidup...',
                'shelf_code' => 'RLG-009',
                'stock' => 9,
            ],
            [
                'title' => 'Perahu Kertas',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-8811-23-5-L.jpg',
                'author' => 'Dewi Lestari (Dee)',
                'publisher' => 'Bentang Pustaka',
                'year' => 2009,
                'isbn' => '978-602-8811-23-5',
                'category' => 'Novel Romantis',
                'synopsis' => 'Kisah dua anak muda yang mencari jati diri...',
                'shelf_code' => 'NVL-010',
                'stock' => 10,
            ],
            [
                'title' => 'Rectoverso',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-979-3062-86-2-L.jpg',
                'author' => 'Dewi Lestari (Dee)',
                'publisher' => 'Bentang Pustaka',
                'year' => 2008,
                'isbn' => '978-979-3062-86-2',
                'category' => 'Kumpulan Cerita',
                'synopsis' => 'Kumpulan cerita dan lagu...',
                'shelf_code' => 'NVL-011',
                'stock' => 7,
            ],
            [
                'title' => 'Dilan: Dia adalah Dilanku Tahun 1990',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-7870-08-0-L.jpg',
                'author' => 'Pidi Baiq',
                'publisher' => 'Pastel Books',
                'year' => 2014,
                'isbn' => '978-602-7870-08-0',
                'category' => 'Novel Remaja',
                'synopsis' => 'Cinta remaja Milea dan Dilan...',
                'shelf_code' => 'NVL-012',
                'stock' => 12,
            ],
            [
                'title' => 'Milea: Suara dari Dilan',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-7870-74-5-L.jpg',
                'author' => 'Pidi Baiq',
                'publisher' => 'Pastel Books',
                'year' => 2016,
                'isbn' => '978-602-7870-74-5',
                'category' => 'Novel Remaja',
                'synopsis' => 'Kisah cinta Dilan dari sudut pandang Milea...',
                'shelf_code' => 'NVL-013',
                'stock' => 10,
            ],
            [
                'title' => 'Hujan',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-0822-66-6-L.jpg',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'year' => 2016,
                'isbn' => '978-602-0822-66-6',
                'category' => 'Fiksi Ilmiah',
                'synopsis' => 'Cerita tentang cinta dan kehilangan di masa depan...',
                'shelf_code' => 'FKS-014',
                'stock' => 9,
            ],
            [
                'title' => 'Pulang',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-0822-16-1-L.jpg',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'year' => 2015,
                'isbn' => '978-602-0822-16-1',
                'category' => 'Fiksi Aksi',
                'synopsis' => 'Perjalanan Bujang...',
                'shelf_code' => 'FKS-015',
                'stock' => 8,
            ],
            [
                'title' => 'Bumi',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-03-0412-8-L.jpg',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2014,
                'isbn' => '978-602-03-0412-8',
                'category' => 'Fantasi',
                'synopsis' => 'Petualangan Raib di dunia paralel...',
                'shelf_code' => 'FNT-016',
                'stock' => 10,
            ],
            [
                'title' => 'Selena',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-06-4501-4-L.jpg',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2020,
                'isbn' => '978-602-06-4501-4',
                'category' => 'Fantasi',
                'synopsis' => 'Spin-off dari seri Bumi...',
                'shelf_code' => 'FNT-017',
                'stock' => 8,
            ],
            [
                'title' => 'The Alchemist',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-0-06-112241-5-L.jpg',
                'author' => 'Paulo Coelho',
                'publisher' => 'HarperCollins',
                'year' => 1988,
                'isbn' => '978-0-06-112241-5',
                'category' => 'Filosofi',
                'synopsis' => 'Kisah Santiago mencari harta karun...',
                'shelf_code' => 'FIL-018',
                'stock' => 6,
            ],
            [
                'title' => 'Atomic Habits',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-0-7352-1129-2-L.jpg',
                'author' => 'James Clear',
                'publisher' => 'Avery',
                'year' => 2018,
                'isbn' => '978-0-7352-1129-2',
                'category' => 'Motivasi',
                'synopsis' => 'Panduan membentuk kebiasaan kecil...',
                'shelf_code' => 'MTV-019',
                'stock' => 11,
            ],
            [
                'title' => 'Filosofi Teras',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-602-412-518-5-L.jpg',
                'author' => 'Henry Manampiring',
                'publisher' => 'Kompas',
                'year' => 2018,
                'isbn' => '978-602-412-518-5',
                'category' => 'Motivasi',
                'synopsis' => 'Buku ini mengenalkan filsafat Stoa...',
                'shelf_code' => 'MTV-020',
                'stock' => 10,
            ],
            [
                'title' => 'Rich Dad Poor Dad',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-1-61268-019-4-L.jpg',
                'author' => 'Robert T. Kiyosaki',
                'publisher' => 'Plata Publishing',
                'year' => 1997,
                'isbn' => '978-1-61268-019-4',
                'category' => 'Bisnis',
                'synopsis' => 'Pelajaran finansial penting...',
                'shelf_code' => 'BSN-021',
                'stock' => 9,
            ],
            [
                'title' => '7 Habits of Highly Effective People',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-0-7432-6951-3-L.jpg',
                'author' => 'Stephen R. Covey',
                'publisher' => 'Free Press',
                'year' => 1989,
                'isbn' => '978-0-7432-6951-3',
                'category' => 'Pengembangan Diri',
                'synopsis' => 'Prinsip universal untuk membangun karakter...',
                'shelf_code' => 'PDN-022',
                'stock' => 7,
            ],
            [
                'title' => 'Belajar Laravel untuk Pemula',
                'cover_image' => 'https://dummyimage.com/400x600/4ade80/ffffff&text=Laravel+Book',
                'author' => 'Wahyudi Saputra',
                'publisher' => 'Informatika Bandung',
                'year' => 2021,
                'isbn' => '978-623-7131-95-8',
                'category' => 'Teknologi',
                'synopsis' => 'Panduan praktis memahami Laravel...',
                'shelf_code' => 'TEK-023',
                'stock' => 10,
            ],
            [
                'title' => 'Python Crash Course',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-1-59327-928-8-L.jpg',
                'author' => 'Eric Matthes',
                'publisher' => 'No Starch Press',
                'year' => 2019,
                'isbn' => '978-1-59327-928-8',
                'category' => 'Pemrograman',
                'synopsis' => 'Panduan lengkap mempelajari Python...',
                'shelf_code' => 'TEK-024',
                'stock' => 9,
            ],
            [
                'title' => 'Clean Code',
                'cover_image' => 'https://covers.openlibrary.org/b/isbn/978-0-13-235088-4-L.jpg',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'year' => 2008,
                'isbn' => '978-0-13-235088-4',
                'category' => 'Pemrograman',
                'synopsis' => 'Buku klasik tentang menulis kode bersih...',
                'shelf_code' => 'TEK-025',
                'stock' => 8,
            ],
        ];

        $categoryMap = [
            'Novel' => 'Fiksi',
            'Novel Inspiratif' => 'Fiksi',
            'Sastra' => 'Fiksi',
            'Religi' => 'Agama',
            'Novel Romantis' => 'Fiksi',
            'Kumpulan Cerita' => 'Fiksi',
            'Novel Remaja' => 'Fiksi',
            'Fiksi Ilmiah' => 'Fiksi',
            'Fiksi Aksi' => 'Fiksi',
            'Fantasi' => 'Fiksi',
            'Filosofi' => 'Non-Fiksi',
            'Motivasi' => 'Non-Fiksi',
            'Bisnis' => 'Non-Fiksi',
            'Pengembangan Diri' => 'Non-Fiksi',
            'Teknologi' => 'Teknologi',
            'Pemrograman' => 'Teknologi',
        ];

        foreach ($books as $item) {
            $categoryName = $categoryMap[$item['category']] ?? 'Fiksi';
            $category = Category::where('name', $categoryName)->first();
            $item['category_id'] = $category?->id ?? 1;
            unset($item['category']);
            Book::create($item);
        }
    }
}
