<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2005,
                'isbn' => '979-3062-79-7',
                'category' => 'Novel',
                'shelf_code' => 'NVL-001',
                'stock' => 10,
            ],
            [
                'title' => 'Bumi Manusia',
                'author' => 'Pramoedya Ananta Toer',
                'publisher' => 'Hasta Mitra',
                'year' => 1980,
                'isbn' => '978-979-97312-3-4',
                'category' => 'Sejarah',
                'shelf_code' => 'SJH-002',
                'stock' => 5,
            ],
            [
                'title' => 'Dasar-Dasar Pemrograman',
                'author' => 'Rinaldi Munir',
                'publisher' => 'Informatika',
                'year' => 2016,
                'isbn' => '978-602-1514-46-9',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-003',
                'stock' => 15,
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2019,
                'isbn' => '978-602-06-3317-6',
                'category' => 'Pengembangan Diri',
                'shelf_code' => 'PD-004',
                'stock' => 8,
            ],
            [
                'title' => 'Sapiens: Riwayat Singkat Umat Manusia',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'KPG',
                'year' => 2017,
                'isbn' => '978-602-424-416-3',
                'category' => 'Sains',
                'shelf_code' => 'SCI-005',
                'stock' => 7,
            ],
            [
                'title' => 'Rich Dad Poor Dad',
                'author' => 'Robert T. Kiyosaki',
                'publisher' => 'Warner Books',
                'year' => 1997,
                'isbn' => '978-0-446-67745-5',
                'category' => 'Bisnis',
                'shelf_code' => 'BSN-006',
                'stock' => 12,
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'Andrew Hunt, David Thomas',
                'publisher' => 'Addison-Wesley',
                'year' => 1999,
                'isbn' => '978-0-201-61622-4',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-007',
                'stock' => 6,
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'publisher' => 'Prentice Hall',
                'year' => 2008,
                'isbn' => '978-0-13-235088-4',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-008',
                'stock' => 0,
            ],
            [
                'title' => 'Filosofi Teras',
                'author' => 'Henry Manampiring',
                'publisher' => 'Kompas',
                'year' => 2018,
                'isbn' => '978-602-481-121-1',
                'category' => 'Filsafat',
                'shelf_code' => 'FIL-009',
                'stock' => 11,
            ],
            [
                'title' => 'Sejarah Indonesia Modern',
                'author' => 'Sartono Kartodirdjo',
                'publisher' => 'Gramedia',
                'year' => 1993,
                'isbn' => '978-979-403-253-1',
                'category' => 'Sejarah',
                'shelf_code' => 'SJH-010',
                'stock' => 4,
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'publisher' => 'Farrar, Straus and Giroux',
                'year' => 2011,
                'isbn' => '978-0-374-27563-1',
                'category' => 'Psikologi',
                'shelf_code' => 'PSI-011',
                'stock' => 10,
            ],
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'publisher' => 'MIT Press',
                'year' => 2009,
                'isbn' => '978-0-262-03384-8',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-012',
                'stock' => 5,
            ],
            // Tambahan buku lainnya
            [
                'title' => 'The Psychology of Money',
                'author' => 'Morgan Housel',
                'publisher' => 'Harriman House',
                'year' => 2020,
                'isbn' => '978-0857197689',
                'category' => 'Bisnis',
                'shelf_code' => 'BSN-013',
                'stock' => 9,
            ],
            [
                'title' => 'Deep Work',
                'author' => 'Cal Newport',
                'publisher' => 'Grand Central Publishing',
                'year' => 2016,
                'isbn' => '978-1455586691',
                'category' => 'Produktivitas',
                'shelf_code' => 'PD-014',
                'stock' => 7,
            ],
            [
                'title' => 'Artificial Intelligence: A Modern Approach',
                'author' => 'Stuart Russell, Peter Norvig',
                'publisher' => 'Pearson',
                'year' => 2021,
                'isbn' => '978-0134610993',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-015',
                'stock' => 3,
            ],
            [
                'title' => 'Homo Deus',
                'author' => 'Yuval Noah Harari',
                'publisher' => 'Harper',
                'year' => 2016,
                'isbn' => '978-0062464316',
                'category' => 'Sains',
                'shelf_code' => 'SCI-016',
                'stock' => 5,
            ],
            [
                'title' => 'Meditations',
                'author' => 'Marcus Aurelius',
                'publisher' => 'Penguin Classics',
                'year' => 2006,
                'isbn' => '978-0140449334',
                'category' => 'Filsafat',
                'shelf_code' => 'FIL-017',
                'stock' => 6,
            ],
            [
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'author' => 'Mark Manson',
                'publisher' => 'HarperOne',
                'year' => 2016,
                'isbn' => '978-0062457714',
                'category' => 'Pengembangan Diri',
                'shelf_code' => 'PD-018',
                'stock' => 8,
            ],
            [
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'publisher' => 'Random House',
                'year' => 2018,
                'isbn' => '978-0399590504',
                'category' => 'Biografi',
                'shelf_code' => 'BIO-019',
                'stock' => 6,
            ],
            [
                'title' => 'Man’s Search for Meaning',
                'author' => 'Viktor E. Frankl',
                'publisher' => 'Beacon Press',
                'year' => 2006,
                'isbn' => '978-0807014295',
                'category' => 'Psikologi',
                'shelf_code' => 'PSI-020',
                'stock' => 10,
            ],
            [
                'title' => 'The Myth of Sisyphus',
                'author' => 'Albert Camus',
                'publisher' => 'Vintage',
                'year' => 1991,
                'isbn' => '978-0679733737',
                'category' => 'Filsafat',
                'shelf_code' => 'FIL-021',
                'stock' => 4,
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'publisher' => 'J. B. Lippincott & Co.',
                'year' => 1960,
                'isbn' => '978-0061120084',
                'category' => 'Novel',
                'shelf_code' => 'NVL-022',
                'stock' => 5,
            ],
            [
                'title' => 'The Art of Computer Programming',
                'author' => 'Donald E. Knuth',
                'publisher' => 'Addison-Wesley',
                'year' => 2011,
                'isbn' => '978-0321751041',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-023',
                'stock' => 2,
            ],
            [
                'title' => 'Algorithms to Live By',
                'author' => 'Brian Christian, Tom Griffiths',
                'publisher' => 'Henry Holt and Co.',
                'year' => 2016,
                'isbn' => '978-1627790369',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-024',
                'stock' => 3,
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'year' => 1949,
                'isbn' => '978-0451524935',
                'category' => 'Novel',
                'shelf_code' => 'NVL-025',
                'stock' => 9,
            ],
            [
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'publisher' => 'Crown Business',
                'year' => 2011,
                'isbn' => '978-0307887894',
                'category' => 'Bisnis',
                'shelf_code' => 'BSN-026',
                'stock' => 6,
            ],
            [
                'title' => 'Outliers',
                'author' => 'Malcolm Gladwell',
                'publisher' => 'Little, Brown and Company',
                'year' => 2008,
                'isbn' => '978-0316017923',
                'category' => 'Psikologi',
                'shelf_code' => 'PSI-027',
                'stock' => 4,
            ],
            [
                'title' => 'Dilan: Dia Adalah Dilanku Tahun 1990',
                'author' => 'Pidi Baiq',
                'publisher' => 'Pastel Books',
                'year' => 2014,
                'isbn' => '978-6027870413',
                'category' => 'Novel',
                'shelf_code' => 'NVL-028',
                'stock' => 12,
            ],
            [
                'title' => 'Negeri 5 Menara',
                'author' => 'Ahmad Fuadi',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2009,
                'isbn' => '978-979-22-4523-8',
                'category' => 'Novel',
                'shelf_code' => 'NVL-029',
                'stock' => 7,
            ],
            [
                'title' => 'Pulang',
                'author' => 'Tere Liye',
                'publisher' => 'Republika',
                'year' => 2015,
                'isbn' => '978-602-0822-76-1',
                'category' => 'Novel',
                'shelf_code' => 'NVL-030',
                'stock' => 4,
            ],
            [
                'title' => 'Bumi',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2014,
                'isbn' => '978-602-03-0468-1',
                'category' => 'Fantasi',
                'shelf_code' => 'FAN-031',
                'stock' => 10,
            ],
            [
                'title' => 'Harry Potter and the Philosopher’s Stone',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'year' => 1997,
                'isbn' => '978-0747532699',
                'category' => 'Fantasi',
                'shelf_code' => 'FAN-032',
                'stock' => 2,
            ],
            [
                'title' => 'Inferno',
                'author' => 'Dan Brown',
                'publisher' => 'Doubleday',
                'year' => 2013,
                'isbn' => '978-0385537858',
                'category' => 'Thriller',
                'shelf_code' => 'THR-033',
                'stock' => 3,
            ],
            [
                'title' => 'Origin',
                'author' => 'Dan Brown',
                'publisher' => 'Doubleday',
                'year' => 2017,
                'isbn' => '978-0385514231',
                'category' => 'Thriller',
                'shelf_code' => 'THR-034',
                'stock' => 2,
            ],
            [
                'title' => 'The 7 Habits of Highly Effective People',
                'author' => 'Stephen R. Covey',
                'publisher' => 'Free Press',
                'year' => 1989,
                'isbn' => '978-0743269513',
                'category' => 'Pengembangan Diri',
                'shelf_code' => 'PD-035',
                'stock' => 9,
            ],
            [
                'title' => 'Start with Why',
                'author' => 'Simon Sinek',
                'publisher' => 'Portfolio',
                'year' => 2009,
                'isbn' => '978-1591846444',
                'category' => 'Bisnis',
                'shelf_code' => 'BSN-036',
                'stock' => 4,
            ],
            [
                'title' => 'Zero to One',
                'author' => 'Peter Thiel',
                'publisher' => 'Crown Business',
                'year' => 2014,
                'isbn' => '978-0804139298',
                'category' => 'Bisnis',
                'shelf_code' => 'BSN-037',
                'stock' => 5,
            ],
            [
                'title' => 'Python Crash Course',
                'author' => 'Eric Matthes',
                'publisher' => 'No Starch Press',
                'year' => 2015,
                'isbn' => '978-1593276034',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-038',
                'stock' => 8,
            ],
            [
                'title' => 'Data Science for Business',
                'author' => 'Foster Provost, Tom Fawcett',
                'publisher' => 'O\'Reilly Media',
                'year' => 2013,
                'isbn' => '978-1449361327',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-039',
                'stock' => 3,
            ],
            [
                'title' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'publisher' => 'Simon & Schuster',
                'year' => 2011,
                'isbn' => '978-1451648539',
                'category' => 'Biografi',
                'shelf_code' => 'BIO-040',
                'stock' => 4,
            ],
            [
                'title' => 'Becoming',
                'author' => 'Michelle Obama',
                'publisher' => 'Crown Publishing',
                'year' => 2018,
                'isbn' => '978-1524763138',
                'category' => 'Biografi',
                'shelf_code' => 'BIO-041',
                'stock' => 5,
            ],
            [
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'publisher' => 'Bantam Books',
                'year' => 1988,
                'isbn' => '978-0553380163',
                'category' => 'Sains',
                'shelf_code' => 'SCI-042',
                'stock' => 0,
            ],
            [
                'title' => 'The Selfish Gene',
                'author' => 'Richard Dawkins',
                'publisher' => 'Oxford University Press',
                'year' => 1976,
                'isbn' => '978-0198788607',
                'category' => 'Sains',
                'shelf_code' => 'SCI-043',
                'stock' => 3,
            ],
            [
                'title' => 'The Power of Now',
                'author' => 'Eckhart Tolle',
                'publisher' => 'New World Library',
                'year' => 1997,
                'isbn' => '978-1577314806',
                'category' => 'Pengembangan Diri',
                'shelf_code' => 'PD-044',
                'stock' => 7,
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'publisher' => 'HarperTorch',
                'year' => 1988,
                'isbn' => '978-0061122415',
                'category' => 'Novel',
                'shelf_code' => 'NVL-045',
                'stock' => 9,
            ],
            [
                'title' => 'Sang Pemimpi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'year' => 2006,
                'isbn' => '978-979-3062-93-9',
                'category' => 'Novel',
                'shelf_code' => 'NVL-046',
                'stock' => 4,
            ],
            [
                'title' => 'The Intelligent Investor',
                'author' => 'Benjamin Graham',
                'publisher' => 'HarperBusiness',
                'year' => 1949,
                'isbn' => '978-0060555665',
                'category' => 'Bisnis',
                'shelf_code' => 'BSN-047',
                'stock' => 2,
            ],
            [
                'title' => 'Machine Learning Yearning',
                'author' => 'Andrew Ng',
                'publisher' => 'Deeplearning.ai',
                'year' => 2018,
                'isbn' => '978-0999735707',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-048',
                'stock' => 1,
            ],
            [
                'title' => 'Matematika Diskrit',
                'author' => 'Rinaldi Munir',
                'publisher' => 'Informatika Bandung',
                'year' => 2019,
                'isbn' => '978-602-6232-32-1',
                'category' => 'Komputer',
                'shelf_code' => 'KOM-049',
                'stock' => 10,
            ],
            [
                'title' => 'Hujan',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'year' => 2016,
                'isbn' => '978-602-033-137-2',
                'category' => 'Novel',
                'shelf_code' => 'NVL-050',
                'stock' => 3,
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}



